/* FoodPet recipe database.
   Pure data — kept as a JS file (not .json) so the app works from file:// too,
   where fetch() of a local JSON is blocked. Shape is plain JSON.

   `items` lists what you would actually put in a basket for that dish — the core
   components only, not salt, oil, lemon or spices. They drive the "my usual shop"
   matching, so every one must exist in the vocabulary at the foot of this file.

   `kcal` is a rough estimate for a normal serving of that dish — the anchor the
   Small / Just right / Big portion buttons multiply. Deliberately approximate:
   this app is for pattern awareness, not precision tracking. */
window.FOODPET_RECIPES = {
  "breakfast": [
    { "id": "b1", "items": ["eggs", "spinach", "sourdough"], "kcal": 420, "name": "Eggs, Greens & Sourdough",
      "prep": "Scramble 2-3 eggs in butter, wilt a handful of spinach in the pan, toast a slice of sourdough.",
      "why": "Eggs first, carb last — protein and fat blunt the glucose rise from the toast." },
    { "id": "b2", "items": ["eggs", "avocado", "sprouted bread"], "kcal": 400, "name": "Avocado & Egg Sprouted Toast",
      "prep": "Boil or fry 2 eggs, mash half an avocado onto sprouted-grain toast, salt and lemon.",
      "why": "Fat plus fibre slows gastric emptying, so morning energy stays flat, not spiky." },
    { "id": "b3", "items": ["eggs", "spinach", "feta"], "kcal": 380, "name": "Spinach & Feta Omelette",
      "prep": "Whisk 3 eggs, pour into a hot pan, scatter spinach and feta, fold after 2 minutes.",
      "why": "A near-zero-carb start keeps the first glucose curve of the day almost level." },
    { "id": "b4", "items": ["cottage cheese", "berries", "flaxseed"], "kcal": 350, "name": "Cottage Cheese & Berry Bowl",
      "prep": "Half a cup of cottage cheese, a handful of berries, a spoon of ground flaxseed.",
      "why": "Casein digests slowly, and the berry fibre keeps fructose gentle." },
    { "id": "b5", "items": ["eggs", "mushrooms"], "kcal": 390, "name": "Mushroom & Egg Skillet",
      "prep": "Pan-fry mushrooms in olive oil, crack 2 eggs over them, lid on for 3 minutes.",
      "why": "Protein-and-fat forward — no glucose spike means no mid-morning crash." },
    { "id": "b6", "items": ["smoked salmon", "avocado", "cucumber"], "kcal": 410, "name": "Smoked Salmon & Avocado Plate",
      "prep": "Smoked salmon, sliced avocado, cucumber, squeeze of lemon. No cooking.",
      "why": "Omega-3 fat plus protein supports steady insulin sensitivity through the morning." },
    { "id": "b7", "items": ["greek yogurt", "walnuts"], "kcal": 430, "name": "Greek Yogurt, Nuts & Cinnamon",
      "prep": "Full-fat Greek yogurt, a small handful of walnuts, a good shake of cinnamon.",
      "why": "Cinnamon nudges insulin sensitivity; the fat and protein flatten the curve." },
    { "id": "b8", "items": ["eggs", "tomatoes", "feta"], "kcal": 380, "name": "Shakshuka Cups",
      "prep": "Simmer tinned tomatoes in a pan, crack in 2 eggs, crumble feta over, lid on for 5 minutes.",
      "why": "Eggs and fat first; the tomato fibre keeps the whole plate low-glycaemic." },
    { "id": "b9", "items": ["kefir", "walnuts", "berries"], "kcal": 360, "name": "Kefir & Walnut Bowl",
      "prep": "Pour kefir over a handful of walnuts and berries.",
      "why": "Fermented dairy plus fat slows absorption and feeds the gut bacteria." },
    { "id": "b10", "items": ["halloumi", "eggs", "rocket"], "kcal": 430, "name": "Halloumi & Egg Plate",
      "prep": "Pan-fry halloumi 2 minutes a side, add a fried egg and a handful of rocket.",
      "why": "Almost no carbohydrate at all — the flattest possible start to the day." },
    { "id": "b11", "items": ["ricotta", "berries", "sourdough"], "kcal": 390, "name": "Ricotta & Berry Toast",
      "prep": "Spread ricotta thickly on one slice of toasted sourdough, top with berries.",
      "why": "Protein spread on the bread, rather than beside it, blunts the starch." },
    { "id": "b12", "items": ["sardines", "sourdough", "avocado"], "kcal": 410, "name": "Sardines on Sourdough",
      "prep": "Mash avocado on toast, lay sardines over the top, black pepper and lemon.",
      "why": "Omega-3 and protein eaten before the bread flattens the curve." },
    { "id": "b13", "items": ["chia", "greek yogurt", "berries"], "kcal": 350, "name": "Overnight Chia Pudding",
      "prep": "Soak 2 tbsp chia in milk overnight; top with yogurt and berries in the morning.",
      "why": "A soluble fibre gel slows everything that follows it." }
  ],
  "midmorning": [
    { "id": "m1", "items": ["greek yogurt", "chia"], "kcal": 200, "name": "Greek Yogurt + Chia",
      "prep": "Stir a tablespoon of chia into Greek yogurt, wait 2 minutes for it to thicken.",
      "why": "Soluble fibre forms a gel that slows sugar absorption." },
    { "id": "m2", "items": ["eggs", "almonds"], "kcal": 190, "name": "Boiled Egg + Almonds",
      "prep": "One boiled egg (batch-boil on Sunday) and about 10 almonds.",
      "why": "Pure protein and fat — bridges to lunch with no glucose dip." },
    { "id": "m3", "items": ["cottage cheese", "cucumber"], "kcal": 180, "name": "Cottage Cheese + Cucumber",
      "prep": "Scoop cottage cheese, slice half a cucumber, crack pepper over it.",
      "why": "High protein, high water, low carb — fullness without a spike." },
    { "id": "m4", "items": ["hummus", "carrot", "capsicum", "celery"], "kcal": 210, "name": "Hummus + Veg Sticks",
      "prep": "Two spoons of hummus with carrot, capsicum and celery sticks.",
      "why": "Legume fibre plus raw veg slows anything you eat next." },
    { "id": "m5", "items": ["cheese", "olives"], "kcal": 220, "name": "Cheese & Olives",
      "prep": "A few cubes of cheddar or haloumi with a small handful of olives.",
      "why": "Fat-forward snacking keeps glucose flat and cravings quiet." },
    { "id": "m6", "items": ["peanut butter", "celery"], "kcal": 200, "name": "Peanut Butter Celery Boats",
      "prep": "Fill celery sticks with a tablespoon of natural peanut butter.",
      "why": "Fibre and fat together — a classic flat-curve snack." },
    { "id": "m7", "items": ["edamame"], "kcal": 190, "name": "Edamame & Sea Salt",
      "prep": "Microwave frozen edamame for 2 minutes, scatter with salt.",
      "why": "Plant protein and fibre in a pod — nothing here to spike." },
    { "id": "m8", "items": ["tuna", "cucumber"], "kcal": 200, "name": "Tuna Cucumber Boats",
      "prep": "Halve a cucumber lengthways, scoop it out, fill with tinned tuna.",
      "why": "Protein and water with next to no carbohydrate." },
    { "id": "m9", "items": ["kefir"], "kcal": 180, "name": "Kefir & Cinnamon",
      "prep": "A glass of kefir with a good shake of cinnamon.",
      "why": "Cinnamon nudges insulin sensitivity; fermented dairy is gentle on digestion." },
    { "id": "m10", "items": ["cheese", "apple"], "kcal": 210, "name": "Cheese & Apple Slices",
      "prep": "Slice an apple and pair it with a couple of cubes of cheese.",
      "why": "Fat alongside fruit sugar keeps the rise slow." },
    { "id": "m11", "items": ["chickpeas"], "kcal": 200, "name": "Roasted Chickpeas",
      "prep": "Dry tinned chickpeas, toss in oil and paprika, oven 15 minutes. Batch them on Sunday.",
      "why": "Fibre and protein together — crunchy without the crash." },
    { "id": "m12", "items": ["turkey", "avocado"], "kcal": 220, "name": "Turkey & Avocado Roll-ups",
      "prep": "Spread avocado onto turkey slices and roll them up.",
      "why": "Lean protein plus fat: full for hours, no glucose bump." }
  ],
  "lunch": [
    { "id": "l1", "items": ["chicken", "salad greens", "quinoa"], "kcal": 520, "name": "Chicken, Greens & Quinoa",
      "prep": "Pre-cooked chicken over a big bowl of greens, quinoa added last, olive oil and lemon.",
      "why": "Veg and protein first, carb last — the same meal, a much smaller spike." },
    { "id": "l2", "items": ["paneer", "spinach", "rice"], "kcal": 540, "name": "Paneer & Spinach with Rice",
      "prep": "Pan-fry paneer cubes, toss with wilted spinach, serve rice on the side and eat it last.",
      "why": "Eating the rice after the protein and fibre halves the glucose peak." },
    { "id": "l3", "items": ["salmon", "broccoli", "sweet potato"], "kcal": 500, "name": "Salmon, Broccoli & Sweet Potato",
      "prep": "Tinned or leftover salmon, steamed broccoli (3 min microwave), sweet potato last.",
      "why": "Omega-3 and fibre first; sweet potato's slow starch lands gently." },
    { "id": "l4", "items": ["lentils", "roast veg", "tahini"], "kcal": 480, "name": "Lentil & Roast Veg Bowl",
      "prep": "Tinned lentils rinsed, leftover roast veg, a spoon of tahini and lemon.",
      "why": "Lentils are protein and fibre in one — famously low glycaemic." },
    { "id": "l5", "items": ["tofu", "frozen veg", "rice"], "kcal": 510, "name": "Tofu Stir-Fry with Rice",
      "prep": "Stir-fry firm tofu and frozen veg in sesame oil, rice on the side, eaten last.",
      "why": "Fibre-first ordering plus vinegar or soy keeps the rice curve modest." },
    { "id": "l6", "items": ["tuna", "chickpeas", "rocket"], "kcal": 470, "name": "Tuna, Chickpea & Rocket Salad",
      "prep": "Tinned tuna, rinsed chickpeas, rocket, olive oil and red wine vinegar.",
      "why": "Vinegar before carbs measurably lowers the post-meal rise." },
    { "id": "l7", "items": ["chicken", "barley", "stock"], "kcal": 490, "name": "Chicken Soup with Barley",
      "prep": "Warm leftover chicken and veg in stock, add a scoop of cooked barley at the end.",
      "why": "Barley's beta-glucan fibre is one of the flattest carbs there is." },
    { "id": "l8", "items": ["chicken", "halloumi", "salad greens"], "kcal": 530, "name": "Chicken & Halloumi Bowl",
      "prep": "Leftover chicken and seared halloumi over greens, olive oil and lemon.",
      "why": "Protein-dense and carb-free — no afternoon dip to manage." },
    { "id": "l9", "items": ["salmon", "soba noodles", "bok choy"], "kcal": 510, "name": "Salmon & Soba Bowl",
      "prep": "Cook soba 4 minutes, wilt bok choy in the same water, flake salmon over. Noodles last.",
      "why": "Buckwheat soba is lower-glycaemic than wheat, and after the protein it lands gently." },
    { "id": "l10", "items": ["eggs", "quinoa", "rocket"], "kcal": 480, "name": "Egg & Quinoa Salad",
      "prep": "Two boiled eggs over rocket with a scoop of cooked quinoa, vinegar dressing.",
      "why": "Vinegar before the carb measurably lowers the post-meal rise." },
    { "id": "l11", "items": ["beef mince", "broccoli", "rice"], "kcal": 540, "name": "Beef & Broccoli with Rice",
      "prep": "Brown mince with garlic, add broccoli, serve rice on the side and eat it last.",
      "why": "Carb last again — the same plate, a much smaller peak." },
    { "id": "l12", "items": ["chickpeas", "feta", "wholegrain wrap"], "kcal": 500, "name": "Chickpea & Feta Wrap",
      "prep": "Crush chickpeas with feta and lemon, roll into a wholegrain wrap with salad.",
      "why": "Legume fibre inside the wrap slows the flour it is wrapped in." },
    { "id": "l13", "items": ["prawns", "avocado", "rice"], "kcal": 520, "name": "Prawn & Avocado Rice Bowl",
      "prep": "Warm prawns through, slice avocado over rice, soy and sesame to finish.",
      "why": "Fat and protein on top of the rice slow how fast it arrives." }
  ],
  "preworkout": [
    { "id": "p1", "items": ["banana", "almond butter"], "kcal": 180, "name": "Banana + Almond Butter",
      "prep": "Half a banana with a teaspoon of almond butter.",
      "why": "Fast carb for fuel, a little fat so it doesn't spike and drop." },
    { "id": "p2", "items": ["rice cakes", "honey"], "kcal": 160, "name": "Rice Cake + Honey",
      "prep": "One rice cake, a thin drizzle of honey, pinch of salt.",
      "why": "Quick-access glucose 45 minutes out — burned by the session, not stored." },
    { "id": "p3", "items": ["dates", "almonds"], "kcal": 190, "name": "Dates + Almonds",
      "prep": "Two dates and about 6 almonds.",
      "why": "Dense quick carbs buffered by nut fat and fibre." },
    { "id": "p4", "items": ["apple", "cheese"], "kcal": 170, "name": "Apple + Small Cheese Cube",
      "prep": "Slice an apple, pair with a small cube of cheese.",
      "why": "Fruit fibre plus fat — energy without the pre-workout jitter." },
    { "id": "p5", "items": ["oats", "honey"], "kcal": 200, "name": "Oat & Honey Half-Bowl",
      "prep": "Quarter cup of quick oats with hot water and a little honey.",
      "why": "Slow-release carb that keeps blood sugar steady mid-session." },
    { "id": "p6", "items": ["grapes", "walnuts"], "kcal": 180, "name": "Grapes + Walnuts",
      "prep": "A small bunch of grapes with a few walnut halves.",
      "why": "Easy-to-digest sugar with fat alongside to soften the curve." },
    { "id": "p7", "items": ["orange", "almonds"], "kcal": 170, "name": "Mandarin & Almonds",
      "prep": "A mandarin and about 8 almonds.",
      "why": "Quick fruit sugar with nut fat, so it does not arrive all at once." },
    { "id": "p8", "items": ["sourdough", "honey"], "kcal": 190, "name": "Honey Toast Half",
      "prep": "Half a slice of sourdough, thin honey, pinch of salt.",
      "why": "Fast carbohydrate 45 minutes out, burned by the session rather than stored." },
    { "id": "p9", "items": ["greek yogurt", "berries"], "kcal": 180, "name": "Small Yogurt & Berries",
      "prep": "Half a cup of Greek yogurt with a few berries.",
      "why": "Light enough not to sit heavily, with protein to steady it." },
    { "id": "p10", "items": ["dried apricots", "walnuts"], "kcal": 200, "name": "Apricots & Walnuts",
      "prep": "Three dried apricots and a few walnut halves.",
      "why": "Dense quick carbs buffered by fat and fibre." },
    { "id": "p11", "items": ["banana", "oats"], "kcal": 200, "name": "Banana Oat Bite",
      "prep": "Mash half a banana into 2 tbsp oats; eat as is, or press into a bar.",
      "why": "Slow-release oats with fast banana sugar — steady through the session." },
    { "id": "p12", "items": ["melon", "feta"], "kcal": 160, "name": "Melon & Feta",
      "prep": "A few cubes of melon with crumbled feta over.",
      "why": "Hydrating and light, with salt and fat to temper the fruit sugar." }
  ],
  "postworkout": [
    { "id": "r1", "items": ["protein powder", "banana"], "kcal": 300, "name": "Protein Shake + Banana",
      "prep": "One scoop of protein in water or milk, blended or shaken with half a banana.",
      "why": "Muscle is most insulin-sensitive now — protein and carb are used, not stored." },
    { "id": "r2", "items": ["greek yogurt", "berries"], "kcal": 280, "name": "Greek Yogurt + Berries",
      "prep": "A cup of Greek yogurt with a handful of berries.",
      "why": "Fast whey protein for repair, berry carbs into depleted muscle." },
    { "id": "r3", "items": ["eggs", "orange"], "kcal": 290, "name": "Boiled Eggs + Fruit",
      "prep": "Two boiled eggs with an orange or a pear.",
      "why": "Complete protein plus light carb inside the recovery window." },
    { "id": "r4", "items": ["cottage cheese", "pineapple"], "kcal": 270, "name": "Cottage Cheese + Pineapple",
      "prep": "Cottage cheese with a few chunks of pineapple.",
      "why": "Casein and whey together, carb replacing what the session used." },
    { "id": "r5", "items": ["milk", "cocoa", "honey"], "kcal": 310, "name": "Chocolate Milk (the real one)",
      "prep": "A glass of milk with a teaspoon of cocoa and a little honey.",
      "why": "The classic 3:1 carb-to-protein recovery ratio, no prep at all." },
    { "id": "r6", "items": ["tuna", "rice cakes"], "kcal": 300, "name": "Tuna on Rice Cakes",
      "prep": "Tinned tuna over two rice cakes with a squeeze of lemon.",
      "why": "Lean protein plus fast carb straight into recovering muscle." },
    { "id": "r7", "items": ["kefir", "banana"], "kcal": 300, "name": "Kefir & Banana Shake",
      "prep": "Blend a glass of kefir with half a banana.",
      "why": "Fast protein and carb into muscle that is primed to take it." },
    { "id": "r8", "items": ["cottage cheese", "berries"], "kcal": 280, "name": "Cottage Cheese & Berries",
      "prep": "Cottage cheese with a handful of berries.",
      "why": "Casein and whey together for repair, with light carb alongside." },
    { "id": "r9", "items": ["chicken", "rice cakes"], "kcal": 310, "name": "Chicken & Rice Cakes",
      "prep": "Leftover chicken piled onto two rice cakes.",
      "why": "Lean protein plus fast carb inside the recovery window." },
    { "id": "r10", "items": ["edamame", "tuna"], "kcal": 290, "name": "Edamame & Tuna",
      "prep": "A bowl of edamame with tinned tuna stirred through.",
      "why": "Two complete proteins with fibre — recovery without heaviness." },
    { "id": "r11", "items": ["protein powder", "greek yogurt"], "kcal": 300, "name": "Protein Yogurt Bowl",
      "prep": "Stir half a scoop of protein powder into Greek yogurt.",
      "why": "A big protein dose exactly when muscle is most insulin-sensitive." },
    { "id": "r12", "items": ["smoked salmon", "rice cakes"], "kcal": 290, "name": "Smoked Salmon Rice Cakes",
      "prep": "Smoked salmon over two rice cakes with lemon.",
      "why": "Omega-3 and protein with just enough carb to refill." }
  ],
  "dinner": [
    { "id": "d1", "items": ["white fish", "asparagus"], "kcal": 400, "name": "Baked Fish, Asparagus & Olive Oil",
      "prep": "Fish fillet and asparagus on a tray, olive oil and lemon, 180C for 12 minutes.",
      "why": "No starch at night keeps overnight glucose and sleep steady." },
    { "id": "d2", "items": ["chicken", "cauliflower", "avocado"], "kcal": 430, "name": "Chicken, Cauliflower & Avocado",
      "prep": "Pan-fry chicken thigh, microwave-steam cauliflower, slice avocado over the top.",
      "why": "Protein and fat with non-starchy veg — a flat evening curve." },
    { "id": "d3", "items": ["prawns", "bok choy"], "kcal": 380, "name": "Shrimp Stir-Fry in Sesame Oil",
      "prep": "Stir-fry prawns and greens in sesame oil with garlic, 6 minutes total.",
      "why": "Very low carb, high protein — nothing to spike before bed." },
    { "id": "d4", "items": ["tofu", "bok choy"], "kcal": 390, "name": "Tofu & Bok Choy",
      "prep": "Sear firm tofu, add bok choy and a splash of tamari, sesame oil to finish.",
      "why": "Plant protein plus fibre, no late starch to carry into the night." },
    { "id": "d5", "items": ["beef mince", "green beans"], "kcal": 450, "name": "Beef & Green Bean Skillet",
      "prep": "Brown lean mince, throw in green beans and garlic, olive oil, 8 minutes.",
      "why": "Iron and protein with fibrous veg — satisfying without a spike." },
    { "id": "d6", "items": ["salmon", "zucchini", "pesto"], "kcal": 440, "name": "Salmon, Zucchini Ribbons & Pesto",
      "prep": "Pan-fry salmon skin-down, peel zucchini into ribbons, warm through with pesto.",
      "why": "Omega-3 fat and non-starchy veg support overnight insulin sensitivity." },
    { "id": "d7", "items": ["eggs", "roast veg"], "kcal": 410, "name": "Egg & Veg Frittata Slice",
      "prep": "Six eggs, any leftover veg, pan 10 minutes with a lid. Leftovers keep for lunch.",
      "why": "Protein-dense and starch-free — dinner that doesn't disturb sleep." },
    { "id": "d8", "items": ["halloumi", "roast veg"], "kcal": 440, "name": "Halloumi & Veg Tray Bake",
      "prep": "Halloumi and whatever veg is in the drawer, olive oil, 200C for 20 minutes.",
      "why": "No starch at night keeps overnight glucose flat." },
    { "id": "d9", "items": ["sardines", "tomatoes", "rocket"], "kcal": 390, "name": "Sardine & Tomato Salad",
      "prep": "Sardines over rocket and tomatoes, olive oil and red wine vinegar.",
      "why": "Omega-3 plus vinegar — both help the evening curve." },
    { "id": "d10", "items": ["turkey", "zucchini"], "kcal": 400, "name": "Turkey & Zucchini Skillet",
      "prep": "Brown turkey mince, add zucchini ribbons and garlic, 8 minutes.",
      "why": "Lean protein with non-starchy veg — light enough to sleep on." },
    { "id": "d11", "items": ["prawns", "cauliflower"], "kcal": 380, "name": "Prawn & Cauliflower Rice",
      "prep": "Stir-fry prawns, add cauliflower rice for the last 3 minutes, sesame oil.",
      "why": "Cauliflower in place of rice removes the evening starch entirely." },
    { "id": "d12", "items": ["chicken", "asparagus"], "kcal": 430, "name": "Chicken & Asparagus Bake",
      "prep": "Chicken thigh and asparagus on a tray, olive oil and lemon, 180C for 25 minutes.",
      "why": "Protein and fat with fibrous veg — a flat night." },
    { "id": "d13", "items": ["tofu", "green beans"], "kcal": 390, "name": "Tofu & Green Bean Stir-Fry",
      "prep": "Sear tofu, add green beans and a splash of tamari, sesame oil to finish.",
      "why": "Plant protein and fibre with no late carbohydrate." }
  ]
};

/* The shopping vocabulary, grouped for the Settings picker. Every `items` entry
   above must appear here, or it could never be ticked and would read as a
   permanent gap in the list. */
window.FOODPET_INGREDIENTS = {
  "Protein": ["eggs","chicken","turkey","beef mince","salmon","smoked salmon","white fish",
              "tuna","sardines","prawns","tofu","paneer","edamame","lentils","chickpeas",
              "protein powder"],
  "Dairy":   ["greek yogurt","kefir","cottage cheese","ricotta","cheese","feta","halloumi","milk"],
  "Veg":     ["spinach","rocket","salad greens","avocado","cucumber","tomatoes","carrot",
              "capsicum","celery","mushrooms","broccoli","cauliflower","asparagus",
              "green beans","bok choy","zucchini","sweet potato","roast veg","frozen veg"],
  "Carbs":   ["sourdough","sprouted bread","wholegrain wrap","quinoa","rice","soba noodles",
              "barley","oats","rice cakes"],
  "Fruit":   ["berries","banana","apple","orange","grapes","melon","pineapple","dates",
              "dried apricots"],
  "Extras":  ["almonds","walnuts","peanut butter","almond butter","chia","flaxseed","hummus",
              "tahini","pesto","olives","honey","cocoa","stock"],
};
