/* FoodPet recipe database.
   Pure data — kept as a JS file (not .json) so the app works from file:// too,
   where fetch() of a local JSON is blocked. Shape is plain JSON. */
window.FOODPET_RECIPES = {
  "breakfast": [
    { "id": "b1", "name": "Eggs, Greens & Sourdough",
      "prep": "Scramble 2-3 eggs in butter, wilt a handful of spinach in the pan, toast a slice of sourdough.",
      "why": "Eggs first, carb last — protein and fat blunt the glucose rise from the toast." },
    { "id": "b2", "name": "Avocado & Egg Sprouted Toast",
      "prep": "Boil or fry 2 eggs, mash half an avocado onto sprouted-grain toast, salt and lemon.",
      "why": "Fat plus fibre slows gastric emptying, so morning energy stays flat, not spiky." },
    { "id": "b3", "name": "Spinach & Feta Omelette",
      "prep": "Whisk 3 eggs, pour into a hot pan, scatter spinach and feta, fold after 2 minutes.",
      "why": "A near-zero-carb start keeps the first glucose curve of the day almost level." },
    { "id": "b4", "name": "Cottage Cheese & Berry Bowl",
      "prep": "Half a cup of cottage cheese, a handful of berries, a spoon of ground flaxseed.",
      "why": "Casein digests slowly, and the berry fibre keeps fructose gentle." },
    { "id": "b5", "name": "Mushroom & Egg Skillet",
      "prep": "Pan-fry mushrooms in olive oil, crack 2 eggs over them, lid on for 3 minutes.",
      "why": "Protein-and-fat forward — no glucose spike means no mid-morning crash." },
    { "id": "b6", "name": "Smoked Salmon & Avocado Plate",
      "prep": "Smoked salmon, sliced avocado, cucumber, squeeze of lemon. No cooking.",
      "why": "Omega-3 fat plus protein supports steady insulin sensitivity through the morning." },
    { "id": "b7", "name": "Greek Yogurt, Nuts & Cinnamon",
      "prep": "Full-fat Greek yogurt, a small handful of walnuts, a good shake of cinnamon.",
      "why": "Cinnamon nudges insulin sensitivity; the fat and protein flatten the curve." }
  ],
  "midmorning": [
    { "id": "m1", "name": "Greek Yogurt + Chia",
      "prep": "Stir a tablespoon of chia into Greek yogurt, wait 2 minutes for it to thicken.",
      "why": "Soluble fibre forms a gel that slows sugar absorption." },
    { "id": "m2", "name": "Boiled Egg + Almonds",
      "prep": "One boiled egg (batch-boil on Sunday) and about 10 almonds.",
      "why": "Pure protein and fat — bridges to lunch with no glucose dip." },
    { "id": "m3", "name": "Cottage Cheese + Cucumber",
      "prep": "Scoop cottage cheese, slice half a cucumber, crack pepper over it.",
      "why": "High protein, high water, low carb — fullness without a spike." },
    { "id": "m4", "name": "Hummus + Veg Sticks",
      "prep": "Two spoons of hummus with carrot, capsicum and celery sticks.",
      "why": "Legume fibre plus raw veg slows anything you eat next." },
    { "id": "m5", "name": "Cheese & Olives",
      "prep": "A few cubes of cheddar or haloumi with a small handful of olives.",
      "why": "Fat-forward snacking keeps glucose flat and cravings quiet." },
    { "id": "m6", "name": "Peanut Butter Celery Boats",
      "prep": "Fill celery sticks with a tablespoon of natural peanut butter.",
      "why": "Fibre and fat together — a classic flat-curve snack." }
  ],
  "lunch": [
    { "id": "l1", "name": "Chicken, Greens & Quinoa",
      "prep": "Pre-cooked chicken over a big bowl of greens, quinoa added last, olive oil and lemon.",
      "why": "Veg and protein first, carb last — the same meal, a much smaller spike." },
    { "id": "l2", "name": "Paneer & Spinach with Rice",
      "prep": "Pan-fry paneer cubes, toss with wilted spinach, serve rice on the side and eat it last.",
      "why": "Eating the rice after the protein and fibre halves the glucose peak." },
    { "id": "l3", "name": "Salmon, Broccoli & Sweet Potato",
      "prep": "Tinned or leftover salmon, steamed broccoli (3 min microwave), sweet potato last.",
      "why": "Omega-3 and fibre first; sweet potato's slow starch lands gently." },
    { "id": "l4", "name": "Lentil & Roast Veg Bowl",
      "prep": "Tinned lentils rinsed, leftover roast veg, a spoon of tahini and lemon.",
      "why": "Lentils are protein and fibre in one — famously low glycaemic." },
    { "id": "l5", "name": "Tofu Stir-Fry with Rice",
      "prep": "Stir-fry firm tofu and frozen veg in sesame oil, rice on the side, eaten last.",
      "why": "Fibre-first ordering plus vinegar or soy keeps the rice curve modest." },
    { "id": "l6", "name": "Tuna, Chickpea & Rocket Salad",
      "prep": "Tinned tuna, rinsed chickpeas, rocket, olive oil and red wine vinegar.",
      "why": "Vinegar before carbs measurably lowers the post-meal rise." },
    { "id": "l7", "name": "Chicken Soup with Barley",
      "prep": "Warm leftover chicken and veg in stock, add a scoop of cooked barley at the end.",
      "why": "Barley's beta-glucan fibre is one of the flattest carbs there is." }
  ],
  "preworkout": [
    { "id": "p1", "name": "Banana + Almond Butter",
      "prep": "Half a banana with a teaspoon of almond butter.",
      "why": "Fast carb for fuel, a little fat so it doesn't spike and drop." },
    { "id": "p2", "name": "Rice Cake + Honey",
      "prep": "One rice cake, a thin drizzle of honey, pinch of salt.",
      "why": "Quick-access glucose 45 minutes out — burned by the session, not stored." },
    { "id": "p3", "name": "Dates + Almonds",
      "prep": "Two dates and about 6 almonds.",
      "why": "Dense quick carbs buffered by nut fat and fibre." },
    { "id": "p4", "name": "Apple + Small Cheese Cube",
      "prep": "Slice an apple, pair with a small cube of cheese.",
      "why": "Fruit fibre plus fat — energy without the pre-workout jitter." },
    { "id": "p5", "name": "Oat & Honey Half-Bowl",
      "prep": "Quarter cup of quick oats with hot water and a little honey.",
      "why": "Slow-release carb that keeps blood sugar steady mid-session." },
    { "id": "p6", "name": "Grapes + Walnuts",
      "prep": "A small bunch of grapes with a few walnut halves.",
      "why": "Easy-to-digest sugar with fat alongside to soften the curve." }
  ],
  "postworkout": [
    { "id": "r1", "name": "Protein Shake + Banana",
      "prep": "One scoop of protein in water or milk, blended or shaken with half a banana.",
      "why": "Muscle is most insulin-sensitive now — protein and carb are used, not stored." },
    { "id": "r2", "name": "Greek Yogurt + Berries",
      "prep": "A cup of Greek yogurt with a handful of berries.",
      "why": "Fast whey protein for repair, berry carbs into depleted muscle." },
    { "id": "r3", "name": "Boiled Eggs + Fruit",
      "prep": "Two boiled eggs with an orange or a pear.",
      "why": "Complete protein plus light carb inside the recovery window." },
    { "id": "r4", "name": "Cottage Cheese + Pineapple",
      "prep": "Cottage cheese with a few chunks of pineapple.",
      "why": "Casein and whey together, carb replacing what the session used." },
    { "id": "r5", "name": "Chocolate Milk (the real one)",
      "prep": "A glass of milk with a teaspoon of cocoa and a little honey.",
      "why": "The classic 3:1 carb-to-protein recovery ratio, no prep at all." },
    { "id": "r6", "name": "Tuna on Rice Cakes",
      "prep": "Tinned tuna over two rice cakes with a squeeze of lemon.",
      "why": "Lean protein plus fast carb straight into recovering muscle." }
  ],
  "dinner": [
    { "id": "d1", "name": "Baked Fish, Asparagus & Olive Oil",
      "prep": "Fish fillet and asparagus on a tray, olive oil and lemon, 180C for 12 minutes.",
      "why": "No starch at night keeps overnight glucose and sleep steady." },
    { "id": "d2", "name": "Chicken, Cauliflower & Avocado",
      "prep": "Pan-fry chicken thigh, microwave-steam cauliflower, slice avocado over the top.",
      "why": "Protein and fat with non-starchy veg — a flat evening curve." },
    { "id": "d3", "name": "Shrimp Stir-Fry in Sesame Oil",
      "prep": "Stir-fry prawns and greens in sesame oil with garlic, 6 minutes total.",
      "why": "Very low carb, high protein — nothing to spike before bed." },
    { "id": "d4", "name": "Tofu & Bok Choy",
      "prep": "Sear firm tofu, add bok choy and a splash of tamari, sesame oil to finish.",
      "why": "Plant protein plus fibre, no late starch to carry into the night." },
    { "id": "d5", "name": "Beef & Green Bean Skillet",
      "prep": "Brown lean mince, throw in green beans and garlic, olive oil, 8 minutes.",
      "why": "Iron and protein with fibrous veg — satisfying without a spike." },
    { "id": "d6", "name": "Salmon, Zucchini Ribbons & Pesto",
      "prep": "Pan-fry salmon skin-down, peel zucchini into ribbons, warm through with pesto.",
      "why": "Omega-3 fat and non-starchy veg support overnight insulin sensitivity." },
    { "id": "d7", "name": "Egg & Veg Frittata Slice",
      "prep": "Six eggs, any leftover veg, pan 10 minutes with a lid. Leftovers keep for lunch.",
      "why": "Protein-dense and starch-free — dinner that doesn't disturb sleep." }
  ]
};
